/**
 * Browser script for docs.
 *
 * Generated by coz on 6/9/2016,
 * from a template provided by apeman-bud-mock.
 */
'use strict'

import apReact from 'apeman-brws-react'
import DocsComponent from '../components/docs.component.js'

const CONTAINER_ID = 'docs-wrap'

function onload () {
  let { locale } = window
  apReact.render(CONTAINER_ID, DocsComponent, {
    locale
  }, function done () {
    // The component is ready.
  })
  window.removeEventListener('DOMContentLoaded', onload)
}

window.addEventListener('DOMContentLoaded', onload)
