/**
 * Browser script for docs.
 *
 * Generated by coz on 6/9/2016,
 * from a template provided by apeman-bud-mock.
 */
'use strict'

import {mount} from 'sg-react'
import DocsComponent from '../components/docs_component'
import { singleton as redirectService } from '../services/redirect_service'

const CONTAINER_ID = 'docs-wrap'

function onload () {
  window.removeEventListener('DOMContentLoaded', onload)
  redirectService.redirectIfNotAuth()
  let { locale } = window
  mount(CONTAINER_ID, DocsComponent, {
    locale
  }).then(() => {
    // The component is ready.
  })
}

window.addEventListener('DOMContentLoaded', onload)
