/**
 * Component of cases.
 *
 * Generated by coz on 6/9/2016,
 * from a template provided by apeman-bud-mock.
 */

'use strict'

import React from 'react'
import {ApPage, ApMain} from 'apeman-react-basic'
import Header from './fragments/header'
import ShowcaseView from './views/showcase_view'
import {singleton as localeService} from '../services/locale_service'

const { l } = localeService

const CasesComponent = React.createClass({

  render () {
    const s = this
    let { props } = s

    return (
      <ApPage>
        <Header tab='CASES' l={ l }/>
        <ApMain>
          <ShowcaseView l={ l }/>
        </ApMain>
      </ApPage>
    )
  }
})

export default CasesComponent
