/**
 * Component of docs.
 *
 * Generated by coz on 6/9/2016,
 * from a template provided by apeman-bud-mock.
 */

'use strict'

import React from 'react'
import {ApStyle} from 'apeman-react-style'
import {ApPage, ApMain, ApViewStack} from 'apeman-react-basic'

import {ApLocaleMixin} from 'apeman-react-mixins'
import Header from './fragments/header'
import GuideView from './views/guide_view'

const DocsComponent = React.createClass({
  mixins: [
    ApLocaleMixin
  ],
  getInitialState () {
    return {}
  },
  getDefaultProps () {
    return {
      stacker: new (ApViewStack.Stacker)({
        root: GuideView,
        rootProps: {}
      })
    }
  },

  componentWillMount () {
    const s = this
    let { props } = s
    s.registerLocale(props.locale)
  },

  render () {
    const s = this
    let { props } = s
    let l = s.getLocale()
    return (
      <ApPage>
        <Header tab="DOCS"/>
        <ApMain>
          <ApViewStack stacker={ props.stacker }/>
        </ApMain>
      </ApPage>
    )
  }
})

export default DocsComponent
