/**
 * Component of docs.
 *
 * Generated by coz on 6/9/2016,
 * from a template provided by apeman-bud-mock.
 */

'use strict'

import React from 'react'
import {ApStyle} from 'apeman-react-style'
import {ApPage, ApMain} from 'apeman-react-basic'

import Header from './fragments/header'
import GuideView from './views/guide_view'

import {singleton as localeService} from '../services/locale_service'

const { l } = localeService

const DocsComponent = React.createClass({

  render () {
    const s = this
    let { props } = s
    return (
      <ApPage>
        <Header tab="DOCS" l={ l }/>
        <ApMain>
          <GuideView l={ l }/>
        </ApMain>
      </ApPage>
    )
  }
})

export default DocsComponent
